### ISSUE TITLE
Windows cross compilation error when updating zip from 0.5 to 0.6.1

### ISSUE THREAD

**Issue by qarmin** [zip-rs/zip#297]
https://github.com/qarmin/czkawka/runs/5799670892?check_suite_focus=true

```

ed4df9eb00ca0714.exe" "-Wl,--subsystem" "-Wl,windows" "-Wl,--gc-sections" "-no-pie" "-nodefaultlibs" "/home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/rsend.o"
  = note: /usr/bin/x86_64-w64-mingw32-ld: /home/runner/work/czkawka/czkawka/target/x86_64-pc-windows-gnu/debug/deps/libzstd_safe-c8092e449298c0e7.rlib(zstd_safe-c8092e449298c0e7.zstd_safe.b701a353-cgu.12.rcgu.o): in function `zstd_safe::CDict::get_dict_id':
          /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/zstd-safe-4.1.4+zstd.1.5.2/src/lib.rs:1085: undefined reference to `ZSTD_getDictID_fromCDict'
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

**Comment by zamazan4ik** [comment]
Could you please update the `zstd` dependency in zip-rs to the latest version in your copy and then check cross-compilation again? Thanks

My guess is that it could be fixed with just updating to the latest version.

**Comment by qarmin** [comment]
I can't really test it, because zstd is not direct dependency of my crate and in addition I can only test windows build inside CI

**Comment by zamazan4ik** [comment]
Zstd update is merged to the master branch. Please switch your `zip-rs` to the master and check the build again.

**Comment by qarmin** [comment]
With the latest versions of zstd(0.11.1) problem still happens

I opened issue in zstd repository, but for now without any comment - https://github.com/gyscos/zstd-rs/issues/149

**Comment by qarmin** [comment]
Looks that this could be a bug in mingw.
When using gtk4-cross to compile GTK4 app to windows, now everything works fine
